### ISSUE TITLE
Buttons are too small.

### ISSUE THREAD

**Issue by mallick370** [litmuschaos/litmus-ui#39]
The buttons need to have a proper padding . Currently all the buttons are in default padding provided by MUI library.
To know more about button size here's the figma file
[https://www.figma.com/file/Vl4DGJzeLKMMVBpeFzJXmg/Litmus-18-Mar-2021?node-id=578%3A0](url)

**Comment by arkajyotiMukherjee** [comment]
This is expected to arrive on the next release of litmus-ui
v1.1.3

**Comment by whitetiger1399** [comment]
This issue has been fixed with the PR https://github.com/litmuschaos/litmus-ui/pull/71 
Closing the issue.
