### ISSUE TITLE
[MAJOR] Changing the layout of design.

### ISSUE THREAD

**Issue by mallick370** [litmuschaos/litmus-ui#41]
A major change in header has been proposed. 
![Workflows  Main Page](https://user-images.githubusercontent.com/43519140/113910907-fbf7c480-97f6-11eb-807c-ac70660b827d.png)

**Comment by vanshBhatia-A4k9** [comment]
https://github.com/litmuschaos/litmus/pull/2687 was merged and addressed this change. PTAL

**Comment by whitetiger1399** [comment]
This issue is not specific to Litmus-UI and must be addressed in Litmus.

**Comment by whitetiger1399** [comment]
This issue has been fixed with https://github.com/litmuschaos/litmus/pull/2687
Closing the issue. Marking it as fixed.
