### ISSUE TITLE
Changing the active tab text color

### ISSUE THREAD

**Issue by mallick370** [litmuschaos/litmus-ui#45]
As per the design given, it's recommended to give the highlight color to the active tab text.
Current :
![image](https://user-images.githubusercontent.com/43519140/113965247-a5b47100-984a-11eb-8ad3-8bec4c9d69a2.png)

In Design
![image](https://user-images.githubusercontent.com/43519140/113965284-b533ba00-984a-11eb-8a46-e5696f867144.png)

**Comment by whitetiger1399** [comment]
This issue is not specific to Litmus-UI and must be addressed in Litmus.

**Comment by Jonsy13** [comment]
Thanks, @mallick370 
Addressed here https://github.com/litmuschaos/litmus/pull/2698 & https://github.com/litmuschaos/litmus/pull/2693
Closing this issue.
