### ISSUE TITLE
Alignment issues in Argo graph 

### ISSUE THREAD

**Issue by mallick370** [litmuschaos/litmus-ui#51]
![image](https://user-images.githubusercontent.com/43519140/114398052-f9adb580-9bbc-11eb-81ed-e800e754eb53.png)

**Comment by whitetiger1399** [comment]
This issue is not specific to Litmus-UI and must be addressed in Litmus.

**Comment by Jonsy13** [comment]
@mallick370  
Addressed here https://github.com/litmuschaos/litmus/pull/2722
Closing this issue as it is fixed. Thanks @mallick370
